# Este archivo fue generado automáticamente por la CLI de Firebase
# https://github.com/firebase/firebase-tools

# Nombre del workflow que aparecerá en GitHub Actions
name: Deploy to Firebase Hosting on merge

# Evento que dispara el workflow: cuando hay un push a la rama main
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    # El job se ejecuta en la última versión de Ubuntu disponible en GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clona el repositorio en el runner de GitHub Actions
      - uses: actions/checkout@v4

      # Paso 2: Instala las dependencias y construye el proyecto
      - run: npm ci && npm run build
        # 'npm ci' instala dependencias usando package-lock.json (más rápido y reproducible que 'npm install')
        # 'npm run build' ejecuta el script de build definido en package.json

      # Paso 3: Despliega el contenido a Firebase Hosting usando la acción oficial
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }} # Token para permisos en el repo (comentarios, checks, etc)
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLARITA2025_B23DE }} # Credenciales de servicio para Firebase
          channelId: live # Canal de despliegue (live = producción)
          projectId: clarita2025-b23de # ID del proyecto de Firebase
